// Re-export shared types for convenient import inside client
export type {
  Position,
  CharacterNeeds,
  EmotionState,
  ResourceType,
  InventoryItem,
  ActionType,
  CharacterState,
  NPCRole,
  NPCState,
  AnimalType,
  AnimalState,
  Animal,
  BuildingProject,
  Invention,
  TileType,
  WorldTile,
  GameEvent,
  ChatMessage,
  WorldState,
  WSServerMessage,
  WSClientMessage,
} from '@shared/types';
